### PR TITLE
Fix: remove non existing session parameter

### PR DESCRIPTION
**Pull request by yusupova**
### Why

`sessionStorage` parameter does not exist in the `shopifyApi` call, as of v6 of the library there is no `SessionStorage` implementation. So it makes this guide misleading.

### What

Removed `sessionStorage` param and `MemorySessionStorage` from the example guide

### CODE REVIEW

**Comment by mkevinosullivan** [comment]
@yusupova Thanks for finding this error.
1. Please merge/rebase your PR from `main`.
2. Please sign the CLA so that we can approve and merge your PR.

**Comment by yusupova** [comment]
hey @mkevinosullivan , signed CLA and merged with `main` :+1:

**Review by mkevinosullivan — APPROVED** [review]

**Comment by mkevinosullivan** [comment]
@yusupova  We recently added an automated check for ensuring a CHANGELOG entry. Do you mind running the following commands

```shell
yarn changeset --empty
git add .changeset
git commit -m "Add changeset files"
```

and push the changes to the branch, please? This will clear the failing check.

**Comment by yusupova** [comment]
@mkevinosullivan pushed required changes :+1:

**Comment by mkevinosullivan** [comment]
@yusupova Thank you for the contribution 🎉

**Pull request merged**
