### PR TITLE
[Fix] Update session storage doc for correct MySQLSessionStorage connection string

### PR DESCRIPTION
**Pull request by jw-soh**
### WHY are these changes introduced?

Fixes #0000 

The doc has incorrect syntax in the session storage readme.MD file for MySQL.

### WHAT is this pull request doing?

  Updated the correct syntax in the doc to save time for developers who would run into the same issue in future if MySQL was their chosen session storage db.

### CODE REVIEW

**Comment by jw-soh** [comment]
I have signed CLA but can't rerun the actions

**Review by cquemin — COMMENTED** [review]
We will soon-ish publish v6 of `shopify/shopify-api` and session management will be quite different. So I am wondering if this changes is worth keeping?

**Comment by jw-soh** [comment]
@cquemin , if the new v6 fixes the issue then all's good! thanks for the response :)

**Comment by mkevinosullivan** [comment]
This change is no longer mergeable, as the structure of the code base has changed significantly with `v6`, including the removal of `SessionStorage` classes to their own packages in the `Shopify/shopify-app-js` repo.

**Pull request closed without merging**
